name: Unit testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test-env
        python-version: "3.10"
        auto-activate-base: true

    - name: Install dependencies
      run: |
        conda env list
        conda activate test-env
        pip install . --verbose
        conda install -c anaconda pylint
        conda install -c conda-forge pytest-cov

    - name: Run Pylint
      run: |
        pylint --version
