name: Unit testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10

    - name: Create conda environment
      run: |
        conda create -n test-environment python=3.10
        conda activate test-environment

    - name: Install dependencies
      run: |
        pip install . --verbose
        conda install -c anaconda pylint
        conda install -c conda-forge pytest-cov

    - name: Run Pylint
      run: |
        bash lint.sh

    - name: Run unit tests
      run: |
        bash unittest.sh